---
title: "hw04"
author: "Justinhu"
date: "2019年3月25日"
output: html_document
---


```{r}
plot(etf4_returns_xts, xaxt='n')
axis(1, index(etf4_returns_xts), format(index(etf4_returns_xts), "%Y/%m"))
# plot the scatterplot of 0050 and 00646
# convert xts into df using fortify()
library(ggplot2)
etf4_ret.df1<-fortify(etf4_returns_xts)
head(etf4_ret.df1)
plot(etf4_ret.df1$`0050`, etf4_ret.df1$`00646`, pch=20,
     col = 'darkred', main = '0050 vs. 00646 monthly returns',
     xlab = '0050', ylab = '00646 S&P500')
```

```{r}
library(tidyverse)
library(ggplot2)
# convert xts into data frame which can be used by ggplot
# split date index in xts into year, month and day columns 
# using lubridate package
library(lubridate)
etf4_ret.df2 <- cbind(etf4_ret.df1, month=month(index(etf4_returns_xts)), 
                      year=year(index(etf4_returns_xts)))
#
ggplot(data = etf4_ret.df2) +
  geom_point(mapping = aes(x = etf4_ret.df2$`0050`, y = etf4_ret.df2$`0056`, color = month))
#
ggplot(data = etf4_ret.df2) +
  geom_point(mapping = aes(x = etf4_ret.df2$`0050`, y = etf4_ret.df2$`0056`, size = month))
#
ggplot(data = etf4_ret.df2) +
  geom_point(mapping = aes(x = etf4_ret.df2$`0050`, y = etf4_ret.df2$`0056`, alpha = month))
#
etf4_ret
etf4_ret.tmp<-data.frame(date = index(etf4_returns_xts), etf4_ret)
head(etf4_ret.tmp)
```

```{r}
# or you can use the following code
etf4_ret.tmp<-etf4_returns_xts %>% 
  data.frame(date=index(.)) %>% 
  remove_rownames() %>% 
  gather(asset, return, -date) # turn data into long format

head(etf4_ret.tmp)
#
plot(etf4_ret.tmp$X0050, etf4_ret.tmp$X0056)
#
ggplot(etf4_ret.tmp) +
  geom_point(mapping = aes(x = etf4_ret.tmp$`0050`, y = etf4_ret.tmp$`0056`))
#

etf4_ret.df<-fortify(etf4_returns_xts, melt=TRUE)
head(etf4_ret.df)
#
p<-ggplot(etf4_ret.df, aes(x = Index, y = Value))+
  geom_line(aes(color = Series), size = 1)

p + scale_x_date(date_labels = "%Y/%m")

# histogram distribution
q<-etf4_ret.df %>%
  ggplot(aes(x =Value, fill = Series)) +
  geom_histogram(alpha = 0.45, binwidth = .005) +
  ggtitle("Monthly Returns")
q + facet_wrap(~Series)+ theme_update(plot.title = element_text(hjust = 0.5))


# line distribution
etf4_ret.df %>%
  ggplot(aes(x = Value, colour = Series)) +
  geom_density(alpha = 1) +
  ggtitle("Monthly Returns Density Since 2016") +
  xlab("monthly returns") +
  ylab("distribution") +
  theme_update(plot.title = element_text(hjust = 0.5))

# Combine line and histogram together
etf4_ret.df %>%
  ggplot(aes(x = Value)) +
  geom_density(aes(color = Series), alpha = 1) +
  geom_histogram(aes(fill = Series), alpha = 0.45, binwidth = .01) +
  guides(fill = FALSE) +
  facet_wrap(~Series) +
  ggtitle("Monthly Returns Since 2016") +
  xlab("monthly returns") +
  ylab("distribution") +
  theme_update(plot.title = element_text(hjust = 0.5))
```

```{r}
library(plotly)
p1<-plot_ly(etf4_ret.tmp, x = ~date, y=~X0050, name = "0050", type = 'scatter', mode = 'lines') %>%
    add_trace(y=~X0056, name = '0056', mode = 'lines+markers')%>%
    layout(xaxis = list(title ='year'), yaxis = list(title='monthly returns'))
p1
```